In [1]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('play_tennis.csv')
data.drop(columns=['day'],inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

## Problem 1
* Outlook=sunny temp=hot humidity=high wind=weak
- play or not

### Solution 
- P(Yes | sunny,hot,high,weak) = P(sunny | yes) * P(Hot | yes) * P(High | yes) * P(week | yes) * P(yes)
- P(no | sunny,hot,high,weak) = P(sunny | no) * P(Hot | no) * P(High | no) * P(week | no) * P(No)
* compare and decide using the maximum a posteriori rule 

## Problem 2
* Outlook=overcast temp=cold humidity=low wind=weak
- play or not

### Solution 
- P(Yes | overcast,cold,low,weak) = P(overcast | yes) * P(cold | yes) * P(Low | yes) * P(week | yes) * P(yes)
- P(no | overcast,cold,low,weak) = P(overcast | no) * P(cold | no) * P(Low | no) * P(week | no) * P(No)
* compare and decide using the maximum a posteriori rule

In [5]:
# Training

# lookup table (Dictionary)

# Testing

In [6]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [7]:
py = 9/14
pn = 5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [8]:
# Outlook 

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [9]:
Pon = 0
Prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [10]:
# temp

pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [11]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [13]:
# humidity

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [18]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [20]:
# wind

pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [21]:
PStrongNo = 3/5
PWeekNo = 2/5

PStrongYes = 3/9
PWeekYes = 6/9

In [22]:
# Outlook=sunny temp=hot humidity=high wind=weak
Pyes = py * psy * PHotYes * PHighYes * PWeekYes
print(Pyes)

0.007054673721340388

In [23]:
Pno = pn * psn * PHotNo * PHighNo * PWeekNo
print(Pno)

0.02742857142857143

In [ ]:
# So No play