In [100]:
import numpy as np
import pandas as pd

In [101]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [102]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [103]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [104]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression ",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees ",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression  0.9016393442622951
Accuracy of Decision Trees  0.8360655737704918

c:\AI_ML\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [105]:
# For Logistic Reg
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

In [106]:
# For Decision Tree
confusion_matrix(y_test,y_pred2)

array([[25,  7],
       [ 3, 26]])

In [107]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Reg Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(5)

     Actual Label  Logistic Reg Prediction  Decision Tree Prediction
217             0                        0                         0
179             0                        0                         0
160             1                        1                         1
176             0                        0                         0
182             0                        1                         1

In [108]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [109]:
# for logistic reg model
print("Precision ",precision_score(y_test,y_pred1))
print(" recall",recall_score(y_test,y_pred1))
print("f1 ",f1_score(y_test,y_pred1))

Precision  0.8285714285714286
 recall 1.0
f1  0.90625

In [110]:
# for DT reg model
print("Precision ",precision_score(y_test,y_pred2))
print(" recall",recall_score(y_test,y_pred2))
print("f1 ",f1_score(y_test,y_pred2))

Precision  0.7878787878787878
 recall 0.896551724137931
f1  0.8387096774193549

In [111]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [113]:
precision_score(y_test,y_pred2,average=None)

array([0.89285714, 0.78787879])

In [115]:
recall_score(y_test,y_pred2,average=None)

array([0.78125   , 0.89655172])