In [16]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml

In [17]:
data = fetch_openml('mnist_784',version=1,as_frame=False)
df = pd.DataFrame(data = data.data,columns=data.feature_names)
df.insert(0,'label',data.target)

In [18]:
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

c:\AI_ML\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy of Logistic Regression 0.9232142857142858
Accuracy of Decision Trees 0.8725714285714286

In [21]:
print("Logistic Regression confusion matrix")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression confusion matrix

      0     1     2     3     4     5     6     7     8     9
0  1358     0     5     1     3     9     8     4     4     4
1     0  1505     6     5     1     7     1     7    15     2
2     6    20  1227    24    13     8    22    17    31     2
3     8     8    29  1301     1    47     6    14    32    11
4     3     8    11     6  1258     0    14     4    10    49
5     9     8     8    44    12  1100    29     9    31     9
6     7     3    14     2    11    14  1381     2     2     2
7     7     3    14     8    13     3     1  1364     6    46
8    11    24    18    33     3    41     8     3  1174    18
9     6     3     3    16    32    17     0    26    10  1257

In [22]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

      0     1     2     3     4     5     6     7     8     9
0  1309     1    13     7     1    20    19     5    13     8
1     2  1480    10    12     7     5     9     9    11     4
2    24    21  1156    27    17    16    30    23    47     9
3     6    11    41  1221    11    66    11    32    32    26
4     6     3    13     4  1190    12    12    22    30    71
5    17     7    12    58    14  1032    33    10    46    30
6    21     6    17     7    27    27  1308     3    14     8
7     3     5    35    19    18     3     1  1332    10    39
8    24    27    37    35    25    50    24    16  1058    37
9     9     6    14    26    76    31     6    41    31  1130

In [23]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [24]:
precision_score(y_test,y_pred1,average='weighted')

0.9230357644112168

In [33]:
recall_score(y_test,y_pred1,average='weighted')

0.9232142857142858

In [26]:

f1_score(y_test,y_pred1,average='weighted')

0.9230567159226124

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1396
           1       0.95      0.97      0.96      1549
           2       0.92      0.90      0.91      1370
           3       0.90      0.89      0.90      1457
           4       0.93      0.92      0.93      1363
           5       0.88      0.87      0.88      1259
           6       0.94      0.96      0.95      1438
           7       0.94      0.93      0.94      1465
           8       0.89      0.88      0.89      1333
           9       0.90      0.92      0.91      1370

    accuracy                           0.92     14000
   macro avg       0.92      0.92      0.92     14000
weighted avg       0.92      0.92      0.92     14000

In [34]:
f1_score(y_test,y_pred1,average='macro')

0.9219525493832978