## Oridinal encodling

In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.read_csv('customer.csv')
df.sample(5)

    age  gender   review education purchased
39   76    Male     Poor        PG        No
3    72  Female     Good        PG        No
7    60  Female     Poor    School       Yes
28   48    Male     Poor    School        No
44   77  Female  Average        UG        No

In [25]:
df = df.iloc[:,2:]

In [26]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
X_train

     review education
5   Average    School
37  Average        PG
34  Average    School
33     Good        PG
49     Good        UG
15     Poor        UG
27     Poor        PG
16     Poor        UG
21  Average        PG
25     Good    School
47     Good        PG
30  Average        UG
26     Poor        PG
17     Poor        UG
13  Average    School
19     Poor        PG
45     Poor        PG
4   Average        UG
29  Average        UG
0   Average    School
43     Poor        PG
7      Poor    School
39     Poor        PG
20  Average    School
9      Good        UG
3      Good        PG
22     Poor        PG
10     Good        UG
11     Good        UG
38     Good    School
23     Good    School
1      Poor        UG
48     Good        UG
28     Poor    School
12     Poor    School
24  Average        PG
2      Good        PG
31     Poor    School
14     Poor        PG
41     Good        PG

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [32]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [33]:
X_train = oe.transform(X_train)

In [36]:
X_train

array([[1., 0.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.]])

In [37]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le =LabelEncoder()

In [40]:
le.fit(y_train)

LabelEncoder()

In [41]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [42]:
y_train =le.transform(y_train)
y_test =le.transform(y_test)

In [43]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1])